services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: rootpassword
        ports:
            - '3306:3306'
        volumes:
            - mariadb_data:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d

volumes:
    mariadb_data:
